spring:
 profiles: 
  active:
  - dev 
---
spring: 
 profiles: dev #开发环境
 application: 
  name: microserver-configregistroy-dev
---
spring: 
 profiles: test #测试环境
 application: 
  name: microserver-configregistroy-test
#请保存为UTF-8